### ISSUE TITLE
Rate limit plugin doesn't work with go 1.20 without an env variable set

### ISSUE THREAD

**Issue by gaetan-craft** [RussellLuo/caddy-ext#15]
The issue is very similar to #8 which fixed for go1.19 but not go 1.20:
```
caddy 
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.20 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.20 set. Notably, if go1.20 adds a moving garbage collector, this program is unsafe to use.

goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
	go4.org/unsafe/assume-no-moving-gc@v0.0.0-20220617031537-928513b29760/untested.go:25 +0x1ba
```

**Comment by derhuerst** [comment]
I have this problem, too.

Unfortunately, I don't know the Go tooling at all, so I'll ping in here and hope that someone will look at this. 🙂

**Comment by vesamet** [comment]
I'm also facing this issue, sadly :(

**Comment by RussellLuo** [comment]
Sorry for the late reply. I have submitted a PR #16, much appreciated if anyone can give it a try :)

**Comment by love4taylor** [comment]
@RussellLuo I added the module using the `caddy add-package`, but it looks like the problem persists?

```shell
love4taylor@au-tokyo-n1:~$ caddy version
v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=
love4taylor@au-tokyo-n1:~$ sudo caddy add-package github.com/RussellLuo/caddy-ext/ratelimit
2023/05/01 10:15:58.989	INFO	this executable will be replaced	{"path": "/usr/bin/caddy"}
2023/05/01 10:15:58.989	INFO	requesting build	{"os": "linux", "arch": "amd64", "packages": ["github.com/RussellLuo/caddy-ext/ratelimit", "github.com/caddy-dns/cloudflare", "github.com/caddy-dns/dnspod", "github.com/mholt/caddy-webdav", "github.com/WeidiDeng/caddy-cloudflare-ip"]}
2023/05/01 10:15:59.384	INFO	build acquired; backing up current executable	{"current_path": "/usr/bin/caddy", "backup_path": "/usr/bin/caddy.tmp"}
2023/05/01 10:15:59.384	INFO	downloading binary	{"destination": "/usr/bin/caddy"}
2023/05/01 10:16:01.105	INFO	download successful; displaying new binary details	{"location": "/usr/bin/caddy"}

Module versions:

panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.20 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.20 set. Notably, if go1.20 adds a moving garbage collector, this program is unsafe to use.

goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
	go4.org/unsafe/assume-no-moving-gc@v0.0.0-20220617031537-928513b29760/untested.go:25 +0x1ba
Error: download succeeded, but unable to execute 'caddy list-modules': exit status 2
love4taylor@au-tokyo-n1:~$ 
```

**Comment by love4taylor** [comment]
@RussellLuo Maybe you should create a new tag? Even if I compile with xcaddy + go 1.20, if I don't add `@master ` at the end and it defaults to the v0.2.0 tag, the error will still be there.

**Comment by RussellLuo** [comment]
Hi @love4taylor, [ratelimit/v0.3.0](https://github.com/RussellLuo/caddy-ext/releases/tag/ratelimit%2Fv0.3.0) has been released.

**Comment by love4taylor** [comment]
@RussellLuo It's strange. Now `xcaddy` is fine, but `caddy add-package` still doesn't work with the same error. I found a "Rescan" button on caddyserver.com dashbord, maybe because of caching?

**Comment by RussellLuo** [comment]
@love4taylor I just rescanned the package, could you please check if it's okay now?
